title: Xueshan Zhang
logo: /assets/img/xueshan_dresden.png
description: <br>Msc Nanoelectronic System<br><br>Dream to be a software developer who knows hardware the most as well as a hardware engineer who knows software the most;<br><br>Looking for position in the field of Electronics, Semicon, and CS disciplines.<br>
show_downloads: true
google_analytics: UA-255199380-1
theme: jekyll-theme-minimal

Linkedin:
  page_url: https://www.linkedin.com/in/xueshanzhang

Stackoverflow:
  page_url: https://stackoverflow.com/users/17765892/missmango

Github:
  page_url: https://github.com/mangomangomango0820
  cv_url: https://github.com/mangomangomango0820/mangomangomango0820.github.io/blob/main/CV_Xueshan_Zhang_20230605.pdf

CDSN:
  page_url: https://blog.csdn.net/MissMango0820

LeetCode:
  page_url: https://leetcode.com/mangomangomango0820