title: Xueshan Zhang
logo: /assets/img/xueshan_dresden.png
description: <br>Msc Nanoelectronics Graduate<br>Working in Semi Field<br>Looking for phD position with topics in the field of Electronics, Semicon, and CS disciplines.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

Linkedin:
  page_url: https://www.linkedin.com/in/xueshanzhang

Github:
  page_url: https://github.com/mangomangomango0820
  cv_url: https://github.com/mangomangomango0820/mangomangomango0820.github.io/blob/main/CV_Xueshan_Zhang_09212021.pdf