title: Xueshan Zhang
logo: /assets/img/xueshan_dresden.png
description: <br>Msc Nanoelectronics Graduate<br>Working in Semi Field<br>Looking for position  in the field of Electronics, Semicon, and CS disciplines.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

Linkedin:
  page_url: https://www.linkedin.com/in/xueshanzhang

Github:
  page_url: https://github.com/mangomangomango0820
  cv_url: https://github.com/mangomangomango0820/mangomangomango0820.github.io/blob/main/CV_Xueshan_Zhang_03082022.pdf

Stackoverflow:
  page_url: https://stackoverflow.com/users/17765892/missmango

CDSN:
  page_url: https://blog.csdn.net/MissMango0820